export const positions = [
    { id: 1, description: 'CEO' },
    { id: 2, description: 'CTO' },
    { id: 3, description: 'Sales Manager' },
    { id: 4, description: 'Pre Sales Manager' },
    { id: 5, description: 'Marketing' },
    { id: 6, description: 'Enterprise Accounts' },
    { id: 7, description: 'Account Manager' },
    { id: 8, description: 'Marketplace Leader' },
    { id: 9, description: 'Graphic Designer' },
    { id: 10, description: 'Innovation Leader' },
    { id: 11, description: 'Innovation Project Manager' },
    { id: 12, description: 'Project Manager' },
    { id: 13, description: 'Innovation Developer' },
    { id: 14, description: 'Backend Developer' },
    { id: 15, description: 'Human Resources Manager' },
    { id: 16, description: 'General Counter' },
    { id: 17, description: 'Accountant' },
    { id: 18, description: 'Cloud Infraestructure' },
    { id: 19, description: 'Database and Analytics' },
    { id: 20, description: 'SysOps' },
    { id: 21, description: 'Backend Leader' },
    { id: 22, description: 'Frontend Leader' },
    { id: 23, description: 'Frontend Developer' },
  ];